### ISSUE TITLE
Is there a chance Value column will be added in the future?

### ISSUE THREAD

**Issue by chrisonedata** [czetsuya/pse-stockquote-generator#3]
Thank you for this repo. I think it's great.
Is there a chance Value column will be added in the future?

**Comment by czetsuya** [comment]
Hi @chrisonedata, actually the 'value' is already available and just needs to be printed in the CSV.

**Comment by chrisonedata** [comment]
Ok. Thank you for our response.. Java is too high tech for me. I have no clue how to print it in CSV. Amazing how you were even able to do this.

**Comment by czetsuya** [comment]
Oh. I forgot, there's one big problem if you want to get the "value", since I don't save the PDF file from PSE, we cannot reprocess them to recreate the CSV files. Unfortunately, value is not used by Amibroker so I did not export it.
